In [1]:
import torch
import numpy as np

Tensor 与 Numpy 的 ndarray 类似，除了 Tensor 可以运行在 GPU 上或其他的硬件加速设备。

In [3]:
# 直接使用原始数据初始化
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
# 使用 NumPy 数组初始化
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [7]:
# 使用其他的 tensor 初始化
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1987, 0.4981],
        [0.4153, 0.8908]]) 



In [8]:
# 使用随机或常量初始化
shape = (2, 3,)  # 2行3列
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5295, 0.3481, 0.1910],
        [0.9711, 0.3453, 0.8849]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Tensor 的属性包括 shape, datatype 和 device。

In [6]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Tensor 有超过 100 种运算，包括转置、索引、切片、数学运算、线性代数、随机数等。这些运算可以使用 GPU 加速，详见 [Tensor 运算](https://pytorch.org/docs/stable/torch.html)。

In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [2]:
# 标准的类 numpy 的索引和切片
tensor = torch.ones(4, 4)
tensor[:, 1] = 0  # 保留所有行，将第一列的值设置为 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


以下是 tensor 的运算

In [3]:
# 使用 cat 拼接两个 tensor
torch.cat([tensor, tensor, tensor], dim=1)  # 按列拼接

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [4]:
# 使用 mul 进行矩阵乘法（按元素）
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [5]:
# 使用 matmul 进行矩阵乘法
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


带有 _ 的运算会改变 tensor 自身，例如 `x.copy_(y)`，`x.t_()` 将会改变 `x`。

In [6]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [7]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()  # tensor 转换为 numpy，共享底层的内存
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [8]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [9]:
n = np.ones(5)
t = torch.from_numpy(n)  # numpy 转换为 tensor，共享底层的内存
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [8]:
x = torch.randn(3, requires_grad=True)  # requires_grad=True 表示将其标记为需要计算导数
y = x * 2
z = y.mean()  # mean() 是一个标量，因此 z 是一个标量

print(y)
print(z)

z.backward()  # 反向传播
print(x.grad)  # x.grad 是 z 关于 x 的导数

tensor([1.3923, 3.1868, 2.9558], grad_fn=<MulBackward0>)
tensor(2.5116, grad_fn=<MeanBackward0>)
tensor([0.6667, 0.6667, 0.6667])
