In [1]:
import torch

In [2]:
# 梯度的必須是32位或是64位的浮点数，且必须是 n 维矩阵形式，例子中的 2.0 会自动转换乘 [2.0]
w = torch.tensor(2.0, requires_grad=True)
y = w * 3

# w 的梯度值(即為∂y/∂w)
print(w.grad)
y.backward()
print(w.grad)

None
tensor(3.)


In [3]:
# 梯度的必須是32位或是64位的浮点数，且必须是 n 维矩阵形式，例子中的 2.0 会自动转换乘 [2.0]
w = torch.tensor(2.0, requires_grad=True)
y = w * 3

# w 的梯度值(即為∂y/∂w)
print(w.grad)
y.backward()
print(w.grad)

None
tensor(3.)


In [4]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3 * a ** 3 - b ** 2  # 假设 a 和 b 是 NN 的参数，Q 是 loss

# ∂Q/∂a = 9a^2
# ∂Q/∂b = -2b

external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)  # 需要显式地传入 gradient， 它与 Q 的形状(shape)相同
# ∂Q/∂Q = 1

print(9 * a ** 2 == a.grad)
print(-2 * b == b.grad)
print(a.grad)
print(b.grad)


tensor([True, True])
tensor([True, True])
tensor([36., 81.])
tensor([-12.,  -8.])


In [5]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients? : {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

Does `a` require gradients? : False
Does `b` require gradients?: True


In [6]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = x ** 2 + 2
z = torch.sum(y)
print(z)
z.backward()
print(x.grad)  #%%
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3 * a ** 3 - b ** 2  # 假设 a 和 b 是 NN 的参数，Q 是 loss

# ∂Q/∂a = 9a^2
# ∂Q/∂b = -2b

external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)  # 需要显式地传入 gradient， 它与 Q 的形状(shape)相同
# ∂Q/∂Q = 1

print(9 * a ** 2 == a.grad)
print(-2 * b == b.grad)
print(a.grad)
print(b.grad)


tensor(20., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])
tensor([True, True])
tensor([True, True])
tensor([36., 81.])
tensor([-12.,  -8.])


In [7]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients? : {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

Does `a` require gradients? : False
Does `b` require gradients?: True


In [8]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = x ** 2 + 2
z = torch.sum(y)
print(z)
z.backward()
print(x.grad)

tensor(20., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])
