In [2]:
import numpy as np

np.random.seed(12345)
np.set_printoptions(precision=4, suppress=True)

## 初始化

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.array([1, 2, 3])

array([1, 2, 3])

In [7]:
np.ones(5).tolist()

[1.0, 1.0, 1.0, 1.0, 1.0]

In [8]:
np.array([1.0, 2, 3])

array([1., 2., 3.])

In [9]:
np.array([1, 2], dtype=float)

array([1., 2.])

In [10]:
np.array([x for x in range(20) if x % 2 == 0])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# random floats in [0,1]
np.random.random(10)

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [13]:
# random integers
np.random.randint(5, 15, size=10)

array([ 5,  7, 14,  6,  7, 11, 12, 12, 12, 13])

## 索引

In [14]:
x = np.array([10, 20, 30, 40, 50])

In [15]:
x[0]

10

In [16]:
# slice
x[0:2]

array([10, 20])

## 赋值

In [17]:
x2 = x.copy()

In [23]:
x2[0] = 10
x2

array([10, 20, 30, 40, 50])

In [27]:
x2[[1, 2]] = 10
x2

array([10, 10, 10, 40, 50])

In [29]:
# check if the original vector changed
x

array([10, 20, 30, 40, 50])

## 操作

In [30]:
x.sum()

150

In [31]:
x.mean()

30.0

In [32]:
x.max(), x.min()

(50, 10)

In [33]:
# 获取最大元素的索引
x.argmax()

4

In [34]:
np.log(x)

array([2.3026, 2.9957, 3.4012, 3.6889, 3.912 ])

In [35]:
np.exp(x)

array([2.2026e+04, 4.8517e+08, 1.0686e+13, 2.3539e+17, 5.1847e+21])

## 与 list 比较

In [36]:
# log every value as list, one by one
def listlog(vals):
    return [np.log(y) for y in vals]

In [37]:
# get random vector
samp = np.random.random_sample(int(1e7)) + 1
samp

array([1.7372, 1.5968, 1.3637, ..., 1.4525, 1.1466, 1.8769])

In [43]:
%time _ = np.log(samp)

CPU times: total: 78.1 ms
Wall time: 92 ms


In [41]:
%time _ = listlog(samp)

CPU times: total: 1.31 s
Wall time: 4.26 s


# Matrices

In [44]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.array([[1, 2, 3], [4, 5, 6]], dtype='float')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [46]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## 索引

In [51]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
X[0]

array([1, 2, 3])

In [53]:
X[0, 0]

1

In [54]:
# get row
X[0, :]

array([1, 2, 3])

In [55]:
# get column
X[:, 0]

array([1, 4])

In [56]:
# get multiple columns
X[:, [0, 2]]

array([[1, 3],
       [4, 6]])

## 赋值

In [58]:
X2 = X.copy()
X2

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
X2[0, 0] = 10
X2

array([[10,  2,  3],
       [ 4,  5,  6]])

In [61]:
X2[0] = 3
X2

array([[3, 3, 3],
       [4, 5, 6]])

In [63]:
X2[:, -1] = [5, 7]
X2

array([[3, 3, 5],
       [4, 5, 7]])

In [64]:
X

array([[1, 2, 3],
       [4, 5, 6]])

## reshaping

In [67]:
z = np.arange(1, 7)
z, z.shape

(array([1, 2, 3, 4, 5, 6]), (6,))

In [70]:
# 两行三列
Z = z.reshape((2, 3))
Z, Z.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [71]:
Z.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [72]:
Z.flatten()

array([1, 2, 3, 4, 5, 6])

In [73]:
Z.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 数值计算

In [74]:
A = np.array(range(1, 7), dtype=float).reshape(2, 3)
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [77]:
B = np.array([1, 2, 3])
B

array([1, 2, 3])

In [76]:
# not the same as A.dot(B)
A * B

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [78]:
A + B

array([[2., 4., 6.],
       [5., 7., 9.]])

In [79]:
A / B

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [83]:
# matrix multiplication
print(A)
print(B)
A.dot(B)

[[1. 2. 3.]
 [4. 5. 6.]]
[1 2 3]


array([14., 32.])

In [84]:
B.dot(A.T)

array([14., 32.])

In [85]:
A.dot(A.T)

array([[14., 32.],
       [32., 77.]])

In [86]:
# outer product
# multiplying each element of first vector by each element of the second
np.outer(B, B)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

pmatrix ：小括号边框
bmatrix ：中括号边框
Bmatrix ：大括号边框
vmatrix ：单竖线边框
Vmatrix ：双竖线边框
  

上述也就是：
$\begin{bmatrix}
1 & 2 & 3 
\end{bmatrix} \times
\begin{bmatrix}
1 \\
2 \\
3 
\end{bmatrix}$

最后结果是三行三列