In [1]:
import numpy as np

# dot
1. 如果a和b都是一维的,那么结果就是普通的內积(inner product)。可以使用np.matmul 或者 a @ b 得到相同的答案
    $a \cdot b = \sum_{i=1}^{n}{a_ib_i}=a_1b_1 + a_2b_2 + ... + a_nb_n$
2. 如果a和b都是二维的，运算等同于矩阵乘法（Dot product）。可以使用np.matmul 或者 a @ b 得到相同的答案。（位置会改变结果）
3. 如果 a 或者 b 中有一个是标量的，效果等价于np.multiply ，可以使用 multiply(a,b) 或者 a * b 也可以。（位置不会改变结果）
4. 如果a是 N-D 数组, b 是 1-D的数组，结果为a和b最后一个轴的乘积。
5. 如果a是N-D数组， b 是 M-D数组（M>2），结果为a的最后一个轴与a的倒数第二个轴的和。

注意：
- 对于array对象，*和np.multiply函数代表的是数量积，如果希望使用矩阵的乘法规则，则应该调用np.dot和np.matmul函数
- 对于matrix对象，*直接代表了原生的矩阵乘法，而如果特殊情况下需要使用数量积，则应该使用np.multiply函数

In [2]:
# 1-D array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result_ab = np.dot(a, b)
result_ba = np.dot(b, a)
print('result_ab: %s' % (result_ab))
print('result_ba: %s' % (result_ba))

result_ab: 32
result_ba: 32


In [3]:
# 2-D array: 2 x 3
a = np.array([[1, 2, 3], [4, 5, 6]])
# 2-D array: 3 x 2
b = np.array([[1, 2], [3, 4], [5, 6]])

result_ab = np.dot(a, b)
result_ba = np.dot(b, a)
print('dot_result_ab:\n %s' % (result_ab))
print('dot_result_ba:\n %s' % (result_ba))

result_ab = np.matmul(a, b)
result_ba = np.matmul(b, a)
print('matmul_result_ab:\n %s' % (result_ab))
print('matmul_result_ba:\n %s' % (result_ba))

dot_result_ab:
 [[22 28]
 [49 64]]
dot_result_ba:
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]
matmul_result_ab:
 [[22 28]
 [49 64]]
matmul_result_ba:
 [[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [4]:
# 2-D array: 2 x 3
a = np.array([[1, 2, 3], [4, 5, 6]])
# 标量 
b = 3
result_ab = np.dot(a, b)
print('result_ab:\n %s' % (result_ab))

multiply_result_ab = np.multiply(a, b)
print('multiply_result_ab:\n %s' % (multiply_result_ab))

result_ab:
 [[ 3  6  9]
 [12 15 18]]
multiply_result_ab:
 [[ 3  6  9]
 [12 15 18]]


In [5]:
# 2-D array: 2 x 3
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
result_ab = np.dot(a, b)
print('result_ab:\n %s' % (result_ab))

result_ab:
 [14 32]


# matmul
参考 dot 的第二点

# multiply
参考 dot 的第三点