In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.rand(2, 2)
x = Variable(tensor, requires_grad=True)

tensor, x

(tensor([[0.0451, 0.9295],
         [0.6203, 0.1004]]),
 tensor([[0.0451, 0.9295],
         [0.6203, 0.1004]], requires_grad=True))

In [3]:
x.sum(), x.sqrt(), x ** 2, x

(tensor(1.6952, grad_fn=<SumBackward0>),
 tensor([[0.2123, 0.9641],
         [0.7876, 0.3169]], grad_fn=<SqrtBackward0>),
 tensor([[0.0020, 0.8640],
         [0.3847, 0.0101]], grad_fn=<PowBackward0>),
 tensor([[0.0451, 0.9295],
         [0.6203, 0.1004]], requires_grad=True))

In [4]:
x.data

tensor([[0.0451, 0.9295],
        [0.6203, 0.1004]])

In [5]:
x.requires_grad, x.grad, x.grad_fn, x.volatile

C:\Users\ping\AppData\Local\Temp\ipykernel_33896\3032477269.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  x.requires_grad, x.grad, x.grad_fn, x.volatile


(True, None, None, False)

In [6]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)

y = x ** 3 + 3

z = Variable(torch.FloatTensor([5]))

x.requires_grad, y.requires_grad, z.requires_grad, y

(True, True, False, tensor([30.], grad_fn=<AddBackward0>))

In [7]:
y.grad_fn.next_functions[0][0]

In [8]:
y.backward()

In [9]:
x, x.grad

(tensor([3.], requires_grad=True), tensor([27.]))

In [2]:
x = torch.randn(1).requires_grad_(True)

for epoch in range(20):
    y = - x ** 2
    y.backward()
    x.data += 0.1 * x.grad

    # 梯度归零
    x.grad.data.zero_()

    # print當下結果
    print('x = {}, y = {}'.format(x.data.numpy(), -x.data.numpy() ** 2))

x = [1.0929692], y = [-1.1945816]
x = [0.87437534], y = [-0.76453227]
x = [0.69950026], y = [-0.4893006]
x = [0.55960023], y = [-0.31315243]
x = [0.44768018], y = [-0.20041753]
x = [0.35814413], y = [-0.12826721]
x = [0.2865153], y = [-0.08209101]
x = [0.22921224], y = [-0.05253825]
x = [0.18336979], y = [-0.03362448]
x = [0.14669582], y = [-0.02151966]
x = [0.11735666], y = [-0.01377259]
x = [0.09388532], y = [-0.00881445]
x = [0.07510826], y = [-0.00564125]
x = [0.06008661], y = [-0.0036104]
x = [0.04806929], y = [-0.00231066]
x = [0.03845543], y = [-0.00147882]
x = [0.03076435], y = [-0.00094644]
x = [0.02461148], y = [-0.00060572]
x = [0.01968918], y = [-0.00038766]
x = [0.01575135], y = [-0.0002481]


In [4]:
x = torch.linspace(-5, 5, 30)
real_y = x * 3 + 2
weight = torch.randn(1).requires_grad_(True)
bias = torch.randn(1).requires_grad_(True)

opt = torch.optim.SGD(params=[weight, bias], lr=1e-1)
loss_func = torch.nn.MSELoss()

for epoch in range(100):
    pred_y = x * weight + bias
    loss = loss_func(pred_y, real_y)
    opt.zero_grad()
    loss.backward()
    opt.step()

    print('Epoch {}: loss = {}, weight = {}, bias = {}'.format(epoch, loss.data.numpy(),
                                                               weight.data.numpy(), bias.data.numpy()))


Epoch 0: loss = 74.58502960205078, weight = [5.1562476], bias = [-0.0845477]
Epoch 1: loss = 45.76244354248047, weight = [1.3146574], bias = [0.33236185]
Epoch 2: loss = 28.083250045776367, weight = [4.31728], bias = [0.6658895]
Epoch 3: loss = 17.237323760986328, weight = [1.970402], bias = [0.9327116]
Epoch 4: loss = 10.582275390625, weight = [3.8047433], bias = [1.1461693]
Epoch 5: loss = 6.497981548309326, weight = [2.371005], bias = [1.3169354]
Epoch 6: loss = 3.9909093379974365, weight = [3.4916284], bias = [1.4535483]
Epoch 7: loss = 2.4516701698303223, weight = [2.6157389], bias = [1.5628387]
Epoch 8: loss = 1.5064423084259033, weight = [3.300342], bias = [1.6502709]
Epoch 9: loss = 0.9258638620376587, weight = [2.7652497], bias = [1.7202168]
Epoch 10: loss = 0.5691806674003601, weight = [3.1834831], bias = [1.7761734]
Epoch 11: loss = 0.3499969244003296, weight = [2.856588], bias = [1.8209387]
Epoch 12: loss = 0.21527503430843353, weight = [3.1120923], bias = [1.856751]
Epoch 