In [1]:
import torch
from torch.autograd import Variable

In [2]:
tensor = torch.rand(2,2)
x = Variable(tensor, requires_grad=True)

tensor, x

(tensor([[0.0451, 0.9295],
         [0.6203, 0.1004]]),
 tensor([[0.0451, 0.9295],
         [0.6203, 0.1004]], requires_grad=True))

In [3]:
x.sum(), x.sqrt(), x**2, x

(tensor(1.6952, grad_fn=<SumBackward0>),
 tensor([[0.2123, 0.9641],
         [0.7876, 0.3169]], grad_fn=<SqrtBackward0>),
 tensor([[0.0020, 0.8640],
         [0.3847, 0.0101]], grad_fn=<PowBackward0>),
 tensor([[0.0451, 0.9295],
         [0.6203, 0.1004]], requires_grad=True))

In [4]:
x.data

tensor([[0.0451, 0.9295],
        [0.6203, 0.1004]])

In [5]:
x.requires_grad, x.grad, x.grad_fn, x.volatile

C:\Users\ping\AppData\Local\Temp\ipykernel_33896\3032477269.py:1: UserWarning: volatile was removed (Variable.volatile is always False)
  x.requires_grad, x.grad, x.grad_fn, x.volatile


(True, None, None, False)

In [6]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)

y = x**3 + 3

z  = Variable(torch.FloatTensor([5]))

x.requires_grad, y.requires_grad, z.requires_grad, y

(True, True, False, tensor([30.], grad_fn=<AddBackward0>))

In [7]:
y.grad_fn.next_functions[0][0]

In [8]:
y.backward()

In [9]:
x, x.grad

(tensor([3.], requires_grad=True), tensor([27.]))