In [5]:
import numpy as np

my_arr = np.arange(1_000_000)

1.38 ms ± 7.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


使用 `%timeit my_arr2 = my_arr * 2` 可以查看运行时间。

In [32]:
arr = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
arr

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [16]:
arr + arr

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [29]:
arr.shape

(2, 3)

In [34]:
arr.ndimB

2

In [37]:
arr.size

6

In [33]:
arr.dtype

dtype('float64')

In [31]:
np?

In [35]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.arange(15).reshape(3, 5)
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [48]:
from numpy import pi

np.linspace(0, 2, 8)

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [52]:
x = np.linspace(0, 2 * pi, 100)
np.sin(x)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -