In [29]:
import torch
import torch.utils.data as Data
import torchvision
import torchvision.datasets as dsets
import torchvision.transforms as transforms

In [2]:
torch.manual_seed(6)

In [23]:
# Dataset
x = torch.linspace(1, 10, 10)
y = torch.linspace(10, 1, 10)
torch.cat((x.view(len(x), -1), y.view(len(y), -1)), 1)

dataset = Data.TensorDataset(x, y)

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.]))

In [24]:
# DataLoader
BATCH_SIZE = 5

loader = Data.DataLoader(
    dataset=dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=1,
)

In [26]:
for epoch in range(3):
    for step, (batch_x, batch_y) in enumerate(loader):
        print('Epoch : ', epoch, '| Step', step, '| batch x :', batch_x.numpy(), "| batch y : ", batch_y.numpy())

Epoch :  0 | Step 0 | batch x : [2. 6. 1. 7. 4.] | batch y :  [ 9.  5. 10.  4.  7.]
Epoch :  0 | Step 1 | batch x : [ 9. 10.  5.  8.  3.] | batch y :  [2. 1. 6. 3. 8.]
Epoch :  1 | Step 0 | batch x : [9. 2. 7. 8. 3.] | batch y :  [2. 9. 4. 3. 8.]
Epoch :  1 | Step 1 | batch x : [ 5.  6.  4.  1. 10.] | batch y :  [ 6.  5.  7. 10.  1.]
Epoch :  2 | Step 0 | batch x : [8. 2. 6. 3. 9.] | batch y :  [3. 9. 5. 8. 2.]
Epoch :  2 | Step 1 | batch x : [ 4.  1.  7. 10.  5.] | batch y :  [ 7. 10.  4.  1.  6.]


In [27]:
BATCH_SIZE = 8

loader = Data.DataLoader(
    dataset=dataset,  # torch TensorDataset format
    batch_size=BATCH_SIZE,  # mini batch size
    shuffle=True,  # random shuffle for training
    num_workers=1,  # subprocesses for loading data
)

for epoch in range(3):  # train entire dataset 3 times
    for step, (batch_x, batch_y) in enumerate(loader):  # for each training step

        # train your data...

        print('Epoch: ', epoch, '| Step: ', step, '| batch x: ',
              batch_x.numpy(), '| batch y: ', batch_y.numpy())

Epoch:  0 | Step:  0 | batch x:  [ 2. 10.  5.  7.  3.  6.  1.  9.] | batch y:  [ 9.  1.  6.  4.  8.  5. 10.  2.]
Epoch:  0 | Step:  1 | batch x:  [4. 8.] | batch y:  [7. 3.]
Epoch:  1 | Step:  0 | batch x:  [ 1.  7.  3.  4. 10.  9.  5.  6.] | batch y:  [10.  4.  8.  7.  1.  2.  6.  5.]
Epoch:  1 | Step:  1 | batch x:  [8. 2.] | batch y:  [3. 9.]
Epoch:  2 | Step:  0 | batch x:  [ 7. 10.  1.  3.  6.  5.  8.  9.] | batch y:  [ 4.  1. 10.  8.  5.  6.  3.  2.]
Epoch:  2 | Step:  1 | batch x:  [4. 2.] | batch y:  [7. 9.]


In [31]:
# Create dataset from images
img_dir = "./images"
img_data = dsets.ImageFolder(img_dir, transforms.Compose([
    transforms.RandomCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
]))

print(img_data.classes)
print(img_data.class_to_idx)
print(img_data.imgs)

['bird', 'mountain']
{'bird': 0, 'mountain': 1}
[('./images\\bird\\5f708a660eef3c4762c5a4a232f76db0.jpg', 0), ('./images\\bird\\c012c9fc6a99dcc00cfd89867f22a1c6.jpg', 0), ('./images\\mountain\\926c079396486b16944a44e6fa395bd6.jpg', 1), ('./images\\mountain\\b3e291f866f1c8754a5eb7fa51e72a0a.jpg', 1), ('./images\\mountain\\bd5fdf64757acb56a5c336f1e7bdbbb3.jpg', 1), ('./images\\mountain\\f7d40a84a44897f83ab8722254bd0551.jpg', 1)]


In [32]:
# DataLoader
loader = Data.DataLoader(img_data, batch_size=3,
                         shuffle=True, num_workers=1)

for img, label in loader:
    print(img.size())
    print(label)

torch.Size([3, 3, 224, 224])
tensor([0, 1, 1])
torch.Size([3, 3, 224, 224])
tensor([0, 1, 1])


In [33]:
# MNIST Dataset
train_dataset = dsets.MNIST(root='./data',
                            train=True,
                            transform=transforms.ToTensor(),
                            download=True)

image, label = train_dataset[0]
print(image.size())
print(label)

torch.Size([1, 28, 28])
5


In [35]:
train_loader = Data.DataLoader(dataset=train_dataset,
                               batch_size=100,
                               shuffle=True,
                               num_workers=2)

data_iter = iter(train_loader)
images, labels = next(data_iter)

for images, labels in train_loader:
    pass

images.size()

torch.Size([100, 1, 28, 28])

In [36]:
# Custom dataset. You should build custom dataset as below.
class CustomDataset(Data.Dataset):
    def __init__(self):
        # TODO
        # 1. Initialize file path or list of file names.
        pass

    def __getitem__(self, index):
        # TODO
        # 1. Read one data from file (e.g. using numpy.fromfile, PIL.Image.open).
        # 2. Preprocess the data (e.g. torchvision.Transform).
        # 3. Return a data pair (e.g. image and label).
        pass

    def __len__(self):
        # You should change 0 to the total size of your dataset.
        return 0


# Then, you can just use prebuilt torch's data loader.
custom_dataset = CustomDataset()
train_loader = Data.DataLoader(dataset=custom_dataset,
                               batch_size=100,
                               shuffle=True,
                               num_workers=2)

ValueError: num_samples should be a positive integer value, but got num_samples=0

In [44]:
#========================== Using pretrained model ==========================#
# Download and load pretrained resnet.
resnet = torchvision.models.resnet18()

# If you want to finetune only top layer of the model.
for param in resnet.parameters():
    param.requires_grad = False

# Replace top layer for fine-tuning.
resnet.fc = torch.nn.Linear(resnet.fc.in_features, 100)  # 100 is for example.

# For test.
images = torch.autograd.Variable(torch.randn(10, 3, 256, 256))
outputs = resnet(images)
print(outputs.size())  # (10, 100)

torch.Size([10, 100])
